apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.serviceName }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.serviceTargetPort }}
      protocol: TCP
  selector:
    app: {{ .Values.deploymentName }}